package pkg

func IsValidProvider(p string) bool {
	var providerMap = map[string]bool{
		"Topolo": true,
		"Rond":   true,
		"Kildy":  true,
	}
	return providerMap[p]
}

func IsValidVoiceProvider(p string) bool {
	var providerMap = map[string]bool{
		"TransparentCalls": true,
		"E-Voice":          true,
		"JustPhone":        true,
	}
	return providerMap[p]
}

func IsValidEmailProvider(p string) bool {
	var providerMap = map[string]bool{
		"Gmail":      true,
		"Yahoo":      true,
		"Hotmail":    true,
		"MSN":        true,
		"Orange":     true,
		"Comcast":    true,
		"AOL":        true,
		"Live":       true,
		"RediffMail": true,
		"GMX":        true,
		"Protonmail": true,
		"Yandex":     true,
		"Mail.ru":    true,
	}
	return providerMap[p]
}

func IsValidCountryCode(code string) bool {
	// data tacked from http://country.io/names.json
	var data = map[string]bool{
		"BD": true,
		"BE": true,
		"BF": true,
		"BG": true,
		"BA": true,
		"BB": true,
		"WF": true,
		"BL": true,
		"BM": true,
		"BN": true,
		"BO": true,
		"BH": true,
		"BI": true,
		"BJ": true,
		"BT": true,
		"JM": true,
		"BV": true,
		"BW": true,
		"WS": true,
		"BQ": true,
		"BR": true,
		"BS": true,
		"JE": true,
		"BY": true,
		"BZ": true,
		"RU": true,
		"RW": true,
		"RS": true,
		"TL": true,
		"RE": true,
		"TM": true,
		"TJ": true,
		"RO": true,
		"TK": true,
		"GW": true,
		"GU": true,
		"GT": true,
		"GS": true,
		"GR": true,
		"GQ": true,
		"GP": true,
		"JP": true,
		"GY": true,
		"GG": true,
		"GF": true,
		"GE": true,
		"GD": true,
		"GB": true,
		"GA": true,
		"SV": true,
		"GN": true,
		"GM": true,
		"GL": true,
		"GI": true,
		"GH": true,
		"OM": true,
		"TN": true,
		"JO": true,
		"HR": true,
		"HT": true,
		"HU": true,
		"HK": true,
		"HN": true,
		"HM": true,
		"VE": true,
		"PR": true,
		"PS": true,
		"PW": true,
		"PT": true,
		"SJ": true,
		"PY": true,
		"IQ": true,
		"PA": true,
		"PF": true,
		"PG": true,
		"PE": true,
		"PK": true,
		"PH": true,
		"PN": true,
		"PL": true,
		"PM": true,
		"ZM": true,
		"EH": true,
		"EE": true,
		"EG": true,
		"ZA": true,
		"EC": true,
		"IT": true,
		"VN": true,
		"SB": true,
		"ET": true,
		"SO": true,
		"ZW": true,
		"SA": true,
		"ES": true,
		"ER": true,
		"ME": true,
		"MD": true,
		"MG": true,
		"MF": true,
		"MA": true,
		"MC": true,
		"UZ": true,
		"MM": true,
		"ML": true,
		"MO": true,
		"MN": true,
		"MH": true,
		"MK": true,
		"MU": true,
		"MT": true,
		"MW": true,
		"MV": true,
		"MQ": true,
		"MP": true,
		"MS": true,
		"MR": true,
		"IM": true,
		"UG": true,
		"TZ": true,
		"MY": true,
		"MX": true,
		"IL": true,
		"FR": true,
		"IO": true,
		"SH": true,
		"FI": true,
		"FJ": true,
		"FK": true,
		"FM": true,
		"FO": true,
		"NI": true,
		"NL": true,
		"NO": true,
		"NA": true,
		"VU": true,
		"NC": true,
		"NE": true,
		"NF": true,
		"NG": true,
		"NZ": true,
		"NP": true,
		"NR": true,
		"NU": true,
		"CK": true,
		"XK": true,
		"CI": true,
		"CH": true,
		"CO": true,
		"CN": true,
		"CM": true,
		"CL": true,
		"CC": true,
		"CA": true,
		"CG": true,
		"CF": true,
		"CD": true,
		"CZ": true,
		"CY": true,
		"CX": true,
		"CR": true,
		"CW": true,
		"CV": true,
		"CU": true,
		"SZ": true,
		"SY": true,
		"SX": true,
		"KG": true,
		"KE": true,
		"SS": true,
		"SR": true,
		"KI": true,
		"KH": true,
		"KN": true,
		"KM": true,
		"ST": true,
		"SK": true,
		"KR": true,
		"SI": true,
		"KP": true,
		"KW": true,
		"SN": true,
		"SM": true,
		"SL": true,
		"SC": true,
		"KZ": true,
		"KY": true,
		"SG": true,
		"SE": true,
		"SD": true,
		"DO": true,
		"DM": true,
		"DJ": true,
		"DK": true,
		"VG": true,
		"DE": true,
		"YE": true,
		"DZ": true,
		"US": true,
		"UY": true,
		"YT": true,
		"UM": true,
		"LB": true,
		"LC": true,
		"LA": true,
		"TV": true,
		"TW": true,
		"TT": true,
		"TR": true,
		"LK": true,
		"LI": true,
		"LV": true,
		"TO": true,
		"LT": true,
		"LU": true,
		"LR": true,
		"LS": true,
		"TH": true,
		"TF": true,
		"TG": true,
		"TD": true,
		"TC": true,
		"LY": true,
		"VA": true,
		"VC": true,
		"AE": true,
		"AD": true,
		"AG": true,
		"AF": true,
		"AI": true,
		"VI": true,
		"IS": true,
		"IR": true,
		"AM": true,
		"AL": true,
		"AO": true,
		"AQ": true,
		"AS": true,
		"AR": true,
		"AU": true,
		"AT": true,
		"AW": true,
		"IN": true,
		"AX": true,
		"AZ": true,
		"IE": true,
		"ID": true,
		"UA": true,
		"QA": true,
		"MZ": true,
	}
	return data[code]
}

func CodeToName(code string) string {
	var countries = map[string]string{
		"AF": "Afghanistan",
		"AX": "Åland Islands",
		"AL": "Albania",
		"DZ": "Algeria",
		"AS": "American Samoa",
		"AD": "Andorra",
		"AO": "Angola",
		"AI": "Anguilla",
		"AQ": "Antarctica",
		"AG": "Antigua and Barbuda",
		"AR": "Argentina",
		"AM": "Armenia",
		"AW": "Aruba",
		"AU": "Australia",
		"AT": "Austria",
		"AZ": "Azerbaijan",
		"BS": "Bahamas",
		"BH": "Bahrain",
		"BD": "Bangladesh",
		"BB": "Barbados",
		"BY": "Belarus",
		"BE": "Belgium",
		"BZ": "Belize",
		"BJ": "Benin",
		"BM": "Bermuda",
		"BT": "Bhutan",
		"BO": "Bolivia, Plurinational State of",
		"BQ": "Bonaire, Sint Eustatius and Saba",
		"BA": "Bosnia and Herzegovina",
		"BW": "Botswana",
		"BV": "Bouvet Island",
		"BR": "Brazil",
		"IO": "British Indian Ocean Territory",
		"BN": "Brunei Darussalam",
		"BG": "Bulgaria",
		"BF": "Burkina Faso",
		"BI": "Burundi",
		"KH": "Cambodia",
		"CM": "Cameroon",
		"CA": "Canada",
		"CV": "Cape Verde",
		"KY": "Cayman Islands",
		"CF": "Central African Republic",
		"TD": "Chad",
		"CL": "Chile",
		"CN": "China",
		"CX": "Christmas Island",
		"CC": "Cocos (Keeling) Islands",
		"CO": "Colombia",
		"KM": "Comoros",
		"CG": "Congo",
		"CD": "Congo, the Democratic Republic of the",
		"CK": "Cook Islands",
		"CR": "Costa Rica",
		"CI": "Côte d'Ivoire",
		"HR": "Croatia",
		"CU": "Cuba",
		"CW": "Curaçao",
		"CY": "Cyprus",
		"CZ": "Czech Republic",
		"DK": "Denmark",
		"DJ": "Djibouti",
		"DM": "Dominica",
		"DO": "Dominican Republic",
		"EC": "Ecuador",
		"EG": "Egypt",
		"SV": "El Salvador",
		"GQ": "Equatorial Guinea",
		"ER": "Eritrea",
		"EE": "Estonia",
		"ET": "Ethiopia",
		"FK": "Falkland Islands (Malvinas)",
		"FO": "Faroe Islands",
		"FJ": "Fiji",
		"FI": "Finland",
		"FR": "France",
		"GF": "French Guiana",
		"PF": "French Polynesia",
		"TF": "French Southern Territories",
		"GA": "Gabon",
		"GM": "Gambia",
		"GE": "Georgia",
		"DE": "Germany",
		"GH": "Ghana",
		"GI": "Gibraltar",
		"GR": "Greece",
		"GL": "Greenland",
		"GD": "Grenada",
		"GP": "Guadeloupe",
		"GU": "Guam",
		"GT": "Guatemala",
		"GG": "Guernsey",
		"GN": "Guinea",
		"GW": "Guinea-Bissau",
		"GY": "Guyana",
		"HT": "Haiti",
		"HM": "Heard Island and McDonald Islands",
		"VA": "Holy See (Vatican City State)",
		"HN": "Honduras",
		"HK": "Hong Kong",
		"HU": "Hungary",
		"IS": "Iceland",
		"IN": "India",
		"ID": "Indonesia",
		"IR": "Iran, Islamic Republic of",
		"IQ": "Iraq",
		"IE": "Ireland",
		"IM": "Isle of Man",
		"IL": "Israel",
		"IT": "Italy",
		"JM": "Jamaica",
		"JP": "Japan",
		"JE": "Jersey",
		"JO": "Jordan",
		"KZ": "Kazakhstan",
		"KE": "Kenya",
		"KI": "Kiribati",
		"KP": "Korea, Democratic People's Republic of",
		"KR": "Korea, Republic of",
		"KW": "Kuwait",
		"KG": "Kyrgyzstan",
		"LA": "Lao People's Democratic Republic",
		"LV": "Latvia",
		"LB": "Lebanon",
		"LS": "Lesotho",
		"LR": "Liberia",
		"LY": "Libya",
		"LI": "Liechtenstein",
		"LT": "Lithuania",
		"LU": "Luxembourg",
		"MO": "Macao",
		"MK": "Macedonia, the Former Yugoslav Republic of",
		"MG": "Madagascar",
		"MW": "Malawi",
		"MY": "Malaysia",
		"MV": "Maldives",
		"ML": "Mali",
		"MT": "Malta",
		"MH": "Marshall Islands",
		"MQ": "Martinique",
		"MR": "Mauritania",
		"MU": "Mauritius",
		"YT": "Mayotte",
		"MX": "Mexico",
		"FM": "Micronesia, Federated States of",
		"MD": "Moldova, Republic of",
		"MC": "Monaco",
		"MN": "Mongolia",
		"ME": "Montenegro",
		"MS": "Montserrat",
		"MA": "Morocco",
		"MZ": "Mozambique",
		"MM": "Myanmar",
		"NA": "Namibia",
		"NR": "Nauru",
		"NP": "Nepal",
		"NL": "Netherlands",
		"NC": "New Caledonia",
		"NZ": "New Zealand",
		"NI": "Nicaragua",
		"NE": "Niger",
		"NG": "Nigeria",
		"NU": "Niue",
		"NF": "Norfolk Island",
		"MP": "Northern Mariana Islands",
		"NO": "Norway",
		"OM": "Oman",
		"PK": "Pakistan",
		"PW": "Palau",
		"PS": "Palestine, State of",
		"PA": "Panama",
		"PG": "Papua New Guinea",
		"PY": "Paraguay",
		"PE": "Peru",
		"PH": "Philippines",
		"PN": "Pitcairn",
		"PL": "Poland",
		"PT": "Portugal",
		"PR": "Puerto Rico",
		"QA": "Qatar",
		"RE": "Réunion",
		"RO": "Romania",
		"RU": "Russian Federation",
		"RW": "Rwanda",
		"BL": "Saint Barthélemy",
		"SH": "Saint Helena, Ascension and Tristan da Cunha",
		"KN": "Saint Kitts and Nevis",
		"LC": "Saint Lucia",
		"MF": "Saint Martin (French part)",
		"PM": "Saint Pierre and Miquelon",
		"VC": "Saint Vincent and the Grenadines",
		"WS": "Samoa",
		"SM": "San Marino",
		"ST": "Sao Tome and Principe",
		"SA": "Saudi Arabia",
		"SN": "Senegal",
		"RS": "Serbia",
		"SC": "Seychelles",
		"SL": "Sierra Leone",
		"SG": "Singapore",
		"SX": "Sint Maarten (Dutch part)",
		"SK": "Slovakia",
		"SI": "Slovenia",
		"SB": "Solomon Islands",
		"SO": "Somalia",
		"ZA": "South Africa",
		"GS": "South Georgia and the South Sandwich Islands",
		"SS": "South Sudan",
		"ES": "Spain",
		"LK": "Sri Lanka",
		"SD": "Sudan",
		"SR": "Suriname",
		"SJ": "Svalbard and Jan Mayen",
		"SZ": "Swaziland",
		"SE": "Sweden",
		"CH": "Switzerland",
		"SY": "Syrian Arab Republic",
		"TW": "Taiwan, Province of China",
		"TJ": "Tajikistan",
		"TZ": "Tanzania, United Republic of",
		"TH": "Thailand",
		"TL": "Timor-Leste",
		"TG": "Togo",
		"TK": "Tokelau",
		"TO": "Tonga",
		"TT": "Trinidad and Tobago",
		"TN": "Tunisia",
		"TR": "Turkey",
		"TM": "Turkmenistan",
		"TC": "Turks and Caicos Islands",
		"TV": "Tuvalu",
		"UG": "Uganda",
		"UA": "Ukraine",
		"AE": "United Arab Emirates",
		"GB": "United Kingdom",
		"US": "United States",
		"UM": "United States Minor Outlying Islands",
		"UY": "Uruguay",
		"UZ": "Uzbekistan",
		"VU": "Vanuatu",
		"VE": "Venezuela, Bolivarian Republic of",
		"VN": "Viet Nam",
		"VG": "Virgin Islands, British",
		"VI": "Virgin Islands, U.S.",
		"WF": "Wallis and Futuna",
		"EH": "Western Sahara",
		"YE": "Yemen",
		"ZM": "Zambia",
		"ZW": "Zimbabwe",
	}
	return countries[code]
}
